name: prompt-tree
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=1.25.2
  - scikit-learn=1.2.2
  - graphviz=2.50.0
  - jinja2=3.1.2
  - pyyaml=6.0
  - tqdm=4.65.0
  - xgboost=1.7.3
  - pip:
    - openai==0.27.9
